language: node_js
node_js:
  - 8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('123456') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -p 123456
  - sudo service mysql restart
before_script:
  - npm install
script:
  - npm run ci

branches:
  only:
    - master